### ISSUE TITLE
File extension detection for importing midis is case-sensitive.

### ISSUE THREAD

**Issue by MegaScience** [reckhou/MidiBard#8]
**Describe the bug**
When importing midi files, the file explorer will only show midi files. If the file extension is `.mid` it will display correctly, but if the case is different (Example: `.MID`), it won't be displayed. As such, the only way to import them is to mindfully modify the extension to be entirely lowercase.

**To Reproduce**
1. Create a folder with multiple midi files.
2. Have the file extensions as `.mid` and `.MID`.
3. Navigate to this folder with the Import Midi Files window.
4. Only the files with `.mid` will display.

**Expected behavior**
All files with the extension `.mid` should be displayed. However, due to case-sensitivity, files with uppercase characters won't be displayed.

**Comment by reckhou** [comment]
Have tested it and I believe it's Dalamud related. Won't fix but might be fixed in the future Dalamud updates.

To get around with this, right click the `+` button and choose `Win32 File Dialog`

**Comment by reckhou** [comment]
https://github.com/goatcorp/Dalamud/issues/861
